/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as ArticlesIdRouteImport } from './routes/articles/$id'
import { Route as AuthenticatedArticlesIndexRouteImport } from './routes/_authenticated/articles/index'
import { Route as AuthenticatedArticlesNewRouteImport } from './routes/_authenticated/articles/new'
import { Route as AuthenticatedArticlesIdEditRouteImport } from './routes/_authenticated/articles/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArticlesIndexRoute =
  AuthenticatedArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArticlesNewRoute =
  AuthenticatedArticlesNewRouteImport.update({
    id: '/articles/new',
    path: '/articles/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArticlesIdEditRoute =
  AuthenticatedArticlesIdEditRouteImport.update({
    id: '/articles/$id/edit',
    path: '/articles/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof AuthenticatedArticlesNewRoute
  '/articles/': typeof AuthenticatedArticlesIndexRoute
  '/articles/$id/edit': typeof AuthenticatedArticlesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/articles/new': typeof AuthenticatedArticlesNewRoute
  '/articles': typeof AuthenticatedArticlesIndexRoute
  '/articles/$id/edit': typeof AuthenticatedArticlesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/_authenticated/articles/new': typeof AuthenticatedArticlesNewRoute
  '/_authenticated/articles/': typeof AuthenticatedArticlesIndexRoute
  '/_authenticated/articles/$id/edit': typeof AuthenticatedArticlesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/articles/$id'
    | '/articles/new'
    | '/articles/'
    | '/articles/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/articles/$id'
    | '/articles/new'
    | '/articles'
    | '/articles/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_guest'
    | '/_guest/login'
    | '/_guest/signup'
    | '/articles/$id'
    | '/_authenticated/articles/new'
    | '/_authenticated/articles/'
    | '/_authenticated/articles/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ArticlesIdRoute: typeof ArticlesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/articles/': {
      id: '/_authenticated/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof AuthenticatedArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles/new': {
      id: '/_authenticated/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof AuthenticatedArticlesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles/$id/edit': {
      id: '/_authenticated/articles/$id/edit'
      path: '/articles/$id/edit'
      fullPath: '/articles/$id/edit'
      preLoaderRoute: typeof AuthenticatedArticlesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArticlesNewRoute: typeof AuthenticatedArticlesNewRoute
  AuthenticatedArticlesIndexRoute: typeof AuthenticatedArticlesIndexRoute
  AuthenticatedArticlesIdEditRoute: typeof AuthenticatedArticlesIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArticlesNewRoute: AuthenticatedArticlesNewRoute,
  AuthenticatedArticlesIndexRoute: AuthenticatedArticlesIndexRoute,
  AuthenticatedArticlesIdEditRoute: AuthenticatedArticlesIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ArticlesIdRoute: ArticlesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
